---
image: archlinux
secrets:
  - ae5292da-26ac-47e8-a81d-7565c4f35697
  - d364323f-1d50-49ad-8639-706df644d8c0
sources:
  - git@git.sr.ht:~ananth/machines
packages:
  - jq
tasks:
  - fetch_gh_host_keys: |
      curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $(cat ~/github_pat)" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/meta \
      | jq -r '.ssh_keys[] | "github.com \(.)"' \
      >> ~/.ssh/known_hosts

  - mirror: |
      git -C machines push --mirror git@github.com:ananthb/machines
