---
keys:
  - &admin_ananth 4F0758D4AAE24E6D5A4483C666A20525398E18D7
  - &host_discovery age10ptm7gkn0kx9033r4zmqsx7l65emghg3vnme3xfdxw4an0ys8ccsafaaar
  - &host_discovery_user_ananth age15mlx0pyzj3kc66dwum5jyd3kpmknltcz7g2qva9uqehz5fq9f5sq63pstl
  - &host_endeavour age15sfhayymtkzunzc3j3t6pd8r33qmmzmgurqsak0tvq7hdmg5fygsuwmwkl
  - &host_endeavour_user_ananth age1vtrxhmcalay5n503w4zp892sa8d2tvhk78y2k59tl9hdwdzk2yvqulufkp
  - &host_enterprise age12759v6kxah06ru6ca8lj9mavz7ez0tahhqrnc4k0puuylm7h84ssx8ww4x
  - &host_enterprise_user_ananth age1e7yll6e4wde6xurslns2ez49kj8saxhs5mjw9h0z35eapm2cf5dqy3a0j7
  - &host_stargazer age109kaxnxcjfqyfcr49jrvg8tqcgugk0amp4e23ru3300zexhdqfxsp6xwde
  - &host_stargazer_user_ananth age1y8zedseruffw5hgczc5fna4y6t5ul8u93kct5ztt2rlajezd9drskam9pk
  - &host_voyager age13hhdcqa4dcn49w5uy03vfxd2lgurhep53tufawc3gyvc3q9lwf5qs4uu09
  - &host_voyager_user_ananth age1ecj27gptwns0tlm9t9kphhcf7ngkhgzwa8pg7nc5559v96lxzf9qxr6v5q
creation_rules:
  - path_regex: secrets/discovery.yaml$
    key_groups:
      - pgp:
          - *admin_ananth
        age:
          - *host_discovery
          - *host_discovery_user_ananth

  - path_regex: secrets/endeavour.yaml$
    key_groups:
      - pgp:
          - *admin_ananth
        age:
          - *host_endeavour
          - *host_endeavour_user_ananth

  - path_regex: secrets/enterprise.yaml$
    key_groups:
      - pgp:
          - *admin_ananth
        age:
          - *host_enterprise
          - *host_enterprise_user_ananth

  - path_regex: secrets/stargazer.yaml$
    key_groups:
      - pgp:
          - *admin_ananth
        age:
          - *host_stargazer
          - *host_stargazer_user_ananth

  - path_regex: secrets/voyager.yaml$
    key_groups:
      - pgp:
          - *admin_ananth
        age:
          - *host_voyager
          - *host_voyager_user_ananth
