#!/bin/bash

if command -v nvim >/dev/null 2>&1; then
  # download vim plug
  plug_vim="$HOME/.config/nvim/autoload/plug.vim"
  if [[ ! -f "$plug_vim" ]]; then
    echo "Downloading vim-plug for neovim"
    curl --create-dirs -fsSLo "$plug_vim" https://raw.github.com/junegunn/vim-plug/master/plug.vim
  fi

  # make neovim pyvenv
  pyvenv="$HOME/.local/share/nvim/pyvenv"
  if [[ ! -f "$pyvenv/bin/python" ]]; then
    python -m venv "$pyvenv"
  fi

  # install and update everything
  $pyvenv/bin/pip install --quiet --upgrade pyvenv
  nvim '+PlugUpgrade' '+PlugClean!' '+PlugUpdate' '+GoInstallBinaries' \
    '+qall'
fi

if command -v tmux >/dev/null 2>&1; then
  tpm="$HOME/.config/tmux/plugins/tpm"
  if [[ ! -d "$tpm" ]]; then
    git clone https://github.com/tmux-plugins/tpm "$tpm"
  fi
fi

