# fly.toml app configuration file generated for actual-white-moon-5023 on 2025-07-14T22:43:59+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'actual-white-moon-5023'
primary_region = 'sin'

[experimental]
  cmd = ['node', '--max-old-space-size=180', 'app.js']
  auto_rollback = true

[build]
  image = 'actualbudget/actual-server:latest'

[env]
  PORT = '5006'
  TINI_SUBREAPER = '1'
  ACTUAL_LOGIN_METHOD = 'openid'
  ACTUAL_ALLOWED_LOGIN_METHODS = 'openid'

[[mounts]]
  source = 'actual_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 5006
  processes = ['app']
  auto_start_machines = true
  auto_stop_machines = true

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'

[[vm]]
  size = 'shared-cpu-1x'
