# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ipv6Token,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
        "usb_storage"
        "uas"
        "sd_mod"
        "sr_mod"
      ];
      kernelModules = [ "kvm-intel" ];
      luks.devices."root".device = "/dev/disk/by-uuid/342c86a9-4b5a-4c14-b7fa-4bfb6e031ee1";
    };
    kernelModules = [ "kvm-intel" ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/root";
      fsType = "btrfs";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/B681-F883";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };

    # NFS mount from endeavour
    "/srv" = {
      device = "endeavour:/srv";
      fsType = "nfs";
    };
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  networking = {
    useDHCP = lib.mkDefault false;
    interfaces.enp86s0.useDHCP = lib.mkDefault false;
    networkmanager.ensureProfiles.profiles.primary = {
      connection = {
        id = "primary";
        type = "ethernet";
        interface-name = "enp86s0";
      };
      ipv4 = {
        method = "auto";
        route-metric = 10;
      };
      ipv6 = {
        method = "auto";
        route-metric = 10;
        token = ipv6Token;
      };
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    enableRedistributableFirmware = true;
    cpu.intel.updateMicrocode = true;
    bluetooth = {
      enable = true;
      powerOnBoot = true;
    };
  };
}
