return {
	-- MASON TOOLS
	{
		"williamboman/mason.nvim",
		config = true,
	},
	{
		"WhoIsSethDaniel/mason-tool-installer.nvim",
		dependencies = { "williamboman/mason.nvim" },
		config = function()
			require("mason-tool-installer").setup({
				ensure_installed = {
					"black",
					"clang-format",
					"cpplint",
					"cspell",
					"delve",
					"elm-format",
					"elm-language-server",
					"glow",
					"gofumpt",
					"goimports",
					"golangci-lint",
					"golines",
					"gopls",
					"isort",
					"jq",
					"jsonlint",
					"lua-language-server",
					"markdownlint",
					"mypy",
					"pylint",
					"shellcheck",
					"shellharden",
					"shfmt",
					"sql-formatter",
					"staticcheck",
					"stylua",
					"vacuum",
					"vale",
					"write-good",
					"yamlfmt",
					"yamllint",
					"zls",
				},
				auto_update = true,
				start_delay = 10000,
				debounce_hours = 5,
			})
		end,
	},
	-- TREESITTER
	{
		"nvim-treesitter/nvim-treesitter",
		dependencies = { "nvim-treesitter/nvim-treesitter-textobjects" },
		config = function()
			require("nvim-treesitter.configs").setup({
				ensure_installed = {
					"c",
					"cpp",
					"css",
					"dockerfile",
					"elm",
					"fish",
					"go",
					"gomod",
					"haskell",
					"javascript",
					"json",
					"lua",
					"make",
					"python",
					"toml",
					"typescript",
					"yaml",
					"zig",
				},
				auto_install = true,
				matchup = {
					enable = true,
				},
			})
		end,
	},
}
