return {
	-- MASON TOOLS
	{
		"williamboman/mason.nvim",
		config = true,
	},
	{
		"WhoIsSethDaniel/mason-tool-installer.nvim",
		dependencies = { "williamboman/mason.nvim" },
		config = function()
			require("mason-tool-installer").setup({
				ensure_installed = {
					"bash-language-server",
					"black",
					"clangd",
					"clang-format",
					"cpplint",
					"cspell",
					"codespell",
					"css-lsp",
					"commitlint",
					"delve",
					"debugpy",
					"dhall-lsp",
					"elm-format",
					"elm-language-server",
					"eslint-lsp",
					"fixjson",
					"fourmolu",
					"glow",
					"gitlint",
					"gofumpt",
					"goimports",
					"golangci-lint",
					"golangci-lint-langserver",
					"golines",
					"gopls",
					"graphql-language-service-cli",
					"haskell-debug-adapter",
					"haskell-language-server",
					"html-lsp",
					"iferr",
					"isort",
					"jdtls",
					"jq",
					"jsonlint",
					"json-lsp",
					"lua-language-server",
					"luaformatter",
					"marksman",
					"markdownlint",
					"mypy",
					"ormolu",
					"prettier",
					"pylint",
					"shellcheck",
					"shellharden",
					"shfmt",
					"sqlfluff",
					"sqlfmt",
					"staticcheck",
					"stylua",
					"tsserver",
					"vacuum",
					"vale",
					"write-good",
					"yamlfmt",
					"yamllint",
					"zls",
				},
				auto_update = true,
				start_delay = 10000,
				debounce_hours = 5,
			})
		end,
	},
	-- TREESITTER
	{
		"nvim-treesitter/nvim-treesitter",
		dependencies = { "nvim-treesitter/nvim-treesitter-textobjects" },
		config = function()
			require("nvim-treesitter.configs").setup({
				ensure_installed = {
					"c",
					"cpp",
					"css",
					"dockerfile",
					"elm",
					"fish",
					"go",
					"gomod",
					"haskell",
					"javascript",
					"json",
					"lua",
					"make",
					"python",
					"query",
					"toml",
					"typescript",
					"vim",
					"vimdoc",
					"yaml",
					"zig",
				},
				auto_install = true,
				matchup = {
					enable = true,
				},
				sync_install = false,
				ignore_install = {},
				modules = {},
			})
		end,
	},
	"b0o/schemastore.nvim",
}
