{
 "title": "Backup Status",
 "tags": [
  "backups",
  "kopia"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Currently Running Backups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kopia_backups_count{job=\"hathi-backups\"}) or vector(0)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Last Backup Per Path",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "kopia_backups_total{job=\"hathi-backups\"}"
    }
   ]
  },
  {
   "title": "Backup Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kopia_backups_count{job=\"hathi-backups\"}",
     "legendFormat": "{{instance}} ({{stage}})"
    }
   ]
  },
  {
   "title": "Last Backup Timestamps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "kopia_backups_total{job=\"hathi-backups\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}