#!/bin/bash

if command -v vim >/dev/null 2>&1; then
  if [ ! -f ~/.vim/autoload/plug.vim ]; then
    echo "Downloading vim-plug for vim"
    curl --create-dirs -fsSLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim
  fi
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
