name: CI

on:
  push:
    branches:
      - main
  release:

jobs:
  ignite:
    name: Transpile Butane to Ignition
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate ignition files
        run: |
          podman run --rm -v $(pwd):/machines:z \
            quay.io/coreos/butane:release -ps -d /machines \
            /machines/getafix.config.bu > getafix.config.ign
      - name: Archive ignition files
        uses: actions/upload-artifact@v3
        with:
          name: ignition-configs
          path: '*.ign'
      - if: startsWith(github.ref, 'refs/tags/')
        name: Add ignition files to release
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          generate_release_notes: true
          files: '*.ign'
