ssh:
    yubikey_5c: ENC[AES256_GCM,data:81XDN+THELecHbkUk3xh1andqC5cdCDEK5n3ZqXHB8Vw6ywcPYo0KWS0E5w9bej0jp9CXCOQasDxx5wTlMaDwkp5G8PUYL/DhgD10F0rBOy/7JOb9JNWVLNxLPr3uOJg2Hz4qZ8Zu4HKTAv7XnREaX/yOfkpRaQrTWrvBgX3uJyVCvZxTLJa9ce0bWBevptDZzjGltc/UFlGOKhXiU1W88mYYQcQgBsFa9NM4QQqhIeSgymS1Ex8l4XGHivXUa+937QXvy4NVj0Ol9BBjvJtwfpxTQiD/fRVU4y7qdkbMvdQdCeDTkzKui5Q0wrQzS1VNQnxYCNjxBmOO0TqORhcC5geGC8PfNbYWsx3dHJkhIYjP5Fx+i1VXRArW9GYPnfRf/icTQmqNS/0Dj27PtJ2tTgxdvK/euFGb3SMiyXcoI/sMFR26OvbxbR++f2hxk9c65mAkT8eG1Xl3ebRM2qh2Wx/bNpf8uw2CI4f62Z3pCLE302MHTM/D2scBSA2leATkXVsndju3iYafmSLOm+rTg4Z3pases9Taq+XRd1fqIttkREJX/96J1NF8iTrman4UblzPBWB99+MBDndMGfhxSVPMf5F5FoLSArobHG3Kmf/vXRqCoi+6M/hswZxlRexQxDHJLOJ6MW7FeQRYRdEEA==,iv:bpdCu4Si/iF7KAtjxc/UXOhROPBrDe1gv/nbYkORNQg=,tag:WymMReKy/UEtmzZVTwWg2g==,type:str]
    yubikey_5c.pub: ENC[AES256_GCM,data:yR2GYGF2TaqDa6iB1XnAvRPZOZ7nLQumtIGsELAUbhCwoPKwGlhwxl9MjFQHIKWfqDeDAaWHPJTSU8xyBuDOENikEgVVk58vzcVPIP96cP72+jHlRBy+nlVDLaTaxJsxXgRjigKHUNETdMNDgwzU5xXaI3+RmXn1TF73YHzDhe1WLnu/VNBE6i/ZUFeAzswtLSaN32FXwEH0DeArbGNcvOLhrvk4VTUezqs=,iv:o7IHEE9Y6OAXytSP/IksBiaxzsK2oUxvySjgQabcb9E=,tag:u1pzdBB6J/xjpkxkkOVV9g==,type:str]
    yubikey_5c_nano: ENC[AES256_GCM,data:6rm9ZCx6CBOtSeHvhkpTtZ/fu66VL3+Cyt2QcJGxwMPFfxSm6qNYNhwax/0Bh18yREipVCWCt5BakPz/qHKnlFoksiCchDUGNyQNuIDggAWJNM8BAUeC1irCvlTiNmNo8AUq6dYpWewrL5XjN49acywPfX0ssmUqKvPGaaedww3NMIU/u29O5e1xTtq3Q5Up/toUumgAmZD50TTd8TmOBOaOWcPox1IAjyRdszTX3NrjJ9EjEPFj6QzV86MIkVgf5OZeaT4vB/ylBwUr17K2UaEnFl+FzaxQIquRPfvz22U7XyTZWTdw06TQMMjVhBVfvEF9ZByzaLMGC/ACWNN5IgaVyqVLqLm8WT/pU/hwz4hRKU3698cdEjf3BJojFLd/gmyzzIuX/jCmTTqHnW/kEoDZOZp7a5ERPNVljT9sroekeraHMpVAU+3f/vNr15q4nZRbmBstwGznesQEX6/QiGArz9tCJrcpBnEm1bISFVF5p9q3JaV0IxQLqtKZI3RXBYn1YTfeJQHn5PSpdSv1GavrtpBRC5N1jW/nQ8lBKBOIpMHFL7jSLJa9I4g2Ba8ujkrZHi1ibM6F5KPdgPTBsYMLYsDi6V5xw6QgwKERTOlZoJL6B9URLRdIMe7tJZjG7sCbj6DpXKYjl9vGGC4UX3cJCh5gAFvQL3KSV8AAsjjbN2YhnRgHZrTPe87d+ScAhZD3zNc5Q1zW,iv:Amo0J1YPDTZTNK4ZHFgtzIGshnYHYezDWwj7Wm3eGi8=,tag:RfljHt+ei8got+hZUasHag==,type:str]
    yubikey_5c_nano.pub: ENC[AES256_GCM,data:pVp145Dy2ouWjEx0gKEZtUxGMMCUqUC+sAWEQhDpLOpOLjB6qFl27c2b/rsoFagA4aVN7v1YphDr87kf3150iGez8+nlQmqoOLxN3GCNoEpzCkWijeZbwINJDbjLJSaVqxaWzmWP0XSNux4SCmrtsKodmyHNwp55pyH5MCZ49VDNDRSHbSMsxDU/P+ZcRRlmr2LQW3pfYeM+tH6MfAZHkBDO6eRrSgsSm4xkXoH+EpKgFXjkX0FZ,iv:/HP30cSO6Up5utaq384ZP3mUHQYodbee8nxLw10Xp0Q=,tag:1zLlCNo1dCYJC1uiTeDmmw==,type:str]
sops:
    age:
        - recipient: age10ptm7gkn0kx9033r4zmqsx7l65emghg3vnme3xfdxw4an0ys8ccsafaaar
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaTlFaE5BNHNHeThQZFB4
            c3liRWlLUnJicnlmR0daL3VHS0xpd0YrOHdZCnpnVTdGcHlvOWVFN1NKU1RLS21h
            N3B5NlFoRWlNMDJoSHlSYllzY2ViemsKLS0tIGNRQ0dvcUlsWmxmU3NJYzdiT2hY
            Wm9oZHRSakpIVHFiZDk4ZE1FaDFSRmcKPu6OvOeftlt+9t5nTwBlmww2NSIN9ADu
            dyY/9SqCWQ6tINEzMCF6LGms9JrqJu6Pk19U486rCJR/OnqFOas8eg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15mlx0pyzj3kc66dwum5jyd3kpmknltcz7g2qva9uqehz5fq9f5sq63pstl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4d1hiR0VIcDg1OWdTSzMr
            SXJzSXhvdE0vclFNZGViWXRIdTN6bDVtZGxFCkIvOTJLUFpuUWlLcFlIa1lIeGxT
            alMyNHZBRFJpV0liQml1OWduNjFtRGcKLS0tIGtGT1psdXZ4TThrVUZaWGprKzMx
            RFo3TGpuY3FWMXcydmdvenhhK1U3T28Kqr5mlXBfxL5ZuJTb1topquyOsV3BObQV
            W2APt/DqxzI8/6m42WCRdHsLBz8xxmw18E8+46MbZF5ZVOP4avMlsQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15sfhayymtkzunzc3j3t6pd8r33qmmzmgurqsak0tvq7hdmg5fygsuwmwkl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPM1hsNWV6WEJiZEE1NThs
            d0lUOWZoREFXMm5kbGhJQm1EclRndkRJUlg0CkVWNWhUVXdwMDdkOWgrT0hyeUc5
            VjNIZmE4RHNQLzNDNjdyTEZhMkt0Sk0KLS0tIGMrSjhva0U2NnpBZ0xBVGZSbUwx
            KzlxOXNaTUJVSGxOMkRqZFVPVEUrdmcKkdIaXx8pg2L+bRueD6g+hpK/qhkHSMwV
            +6A8terkt030jZJMmlMYtcqYZQFiLedhfxErBXjZBVwezOiQlUGIDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vtrxhmcalay5n503w4zp892sa8d2tvhk78y2k59tl9hdwdzk2yvqulufkp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SXdxU0lZc0JkdndhSWpk
            VU9kZE0zcmpNKzBoS3hiaW5jMWFHUGxDMFRjCnRLeGZVNkxETkVzbENCbW8vWVR6
            MUxOWHU0MEdqVndpV0FEczlURzZDeGcKLS0tIGQ3YWtJSWZkMEJPbkhGemVYWmRQ
            NllFajR0NENTQWFTV2w3VWdiY0dRamsKOvLWNrTu9+7ITKzK3QLpTOb6krxgtCjl
            8yGR4u6c0hBPECm6X1RdzY8jSirVlRcfOtauF+S4q2EuKrSnNO7HVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12759v6kxah06ru6ca8lj9mavz7ez0tahhqrnc4k0puuylm7h84ssx8ww4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdElFYTFqbEk3a3Z3NS9E
            ZTdVcWZzRFY1T1dtakpHM2pJZTBVWVp6bFF3Ck5wSXozODdYSjc4dzU1b3d1TUFY
            OHJlUDZ3YlFVWnBuVHBNYnI4VkhCTFEKLS0tIE9DMnJ2S3ZGUHFBRmlYdVBXVWhQ
            dGYweUJiZmNzZ1g0aDB4WlBlTklJcVEK1wdtEwQsFNDV0YmankcP2mTdEaaQaYdw
            7RyyK12Mg7uDKdYhkvqnIvbgAtL35tuedbKy0eoyCjEsgkfp61cq/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e7yll6e4wde6xurslns2ez49kj8saxhs5mjw9h0z35eapm2cf5dqy3a0j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhR3psQS9iMWhjM3Jma2Vi
            SUp0Mm9HVzN5a3pYZllwS0JBWVpURmRCQ3kwCncvSXhXUkZudEkxc0IwV1FVNVhT
            Y2pUR2JTR1ZDTDhTZ25FRy9YK3hXRmMKLS0tIGFOL3JZdElqMDV6R0tjbjROZWg4
            b2Joa292V2wzdmlmTHNjZ3BITGEvY0UKGTyiZ/oOrVNsnS2bIYTfZo3ZJrt6Kal3
            yjrs1Qt5f/DaPy3BxB2t6p8zhZUE12Yg44941tzpTnnvAbxoLGRS5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age109kaxnxcjfqyfcr49jrvg8tqcgugk0amp4e23ru3300zexhdqfxsp6xwde
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSkFRZzhKU096b3Fzby9a
            Ri9aNTFCL01mbXRwUldzb2FWdXRsbW5vZ2xFCk5TaUdmOU9TUnhrb1hmdjUzUkNC
            dzdMQ1E2eXJ4OEQreFlNdGRsMWEydUUKLS0tIDl6TUMrc0EzRlRJb0Vpb1JaZEVE
            akhkVk9DSFFYQWdvWjJVYjdpKzNuelEKMMlvBTDfrmQNhZUnJjSlGfmWsNAI57bN
            DX1aHhcVRhy1YGrOVKQEna+tjYWao9SkGODauXX25GTOxSLRg4dJjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y8zedseruffw5hgczc5fna4y6t5ul8u93kct5ztt2rlajezd9drskam9pk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrczJyaWVSenNkTHNjZlNs
            d0hiMmpZcGN0bFJIUldacjhVbHByVE1xd0ZvCjJ0M1ZuRnByYVp3RjJ1UkVjN2dV
            bHNXTGUzV1JoME8xQys5eWd1SUJnWmMKLS0tIEtFeEZDQWhnRytqUy8yWU94VDhJ
            RDloNVkwQWplQTNrSE9VMGhsZHQ3YlkKJzVG+uT5Lc2y5O/iLiEli9B/lA0AZkEz
            3rELLM/cGwh7pNQRfr+Alabkesj/DYClQRLdiDCX2sGID81dP60O6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13hhdcqa4dcn49w5uy03vfxd2lgurhep53tufawc3gyvc3q9lwf5qs4uu09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMitrQXhNbGdWZVNjeGx2
            VUJCZm9YdkpGYllLZW92aXNRTEJteWpKSzJZCnlvVG4rWHd1cUIrUWIzRUJXaGdp
            VmQxL3J0RGJxdVR5RlJsMkQ3UFJybWMKLS0tIEExVWJuQkUvNGU1UVRGclViZFV1
            NGZ3cDd4WE1jSzRzdUlhN2poaDVMSE0KddNGl4KAog0VfaPcP2Kxs9TVe2K4outE
            vk7NLQvOoVgrzSo5EtmYtceqtZiA3zaA/tigYI/sEEmQD0Ct0mkrfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ecj27gptwns0tlm9t9kphhcf7ngkhgzwa8pg7nc5559v96lxzf9qxr6v5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMDZXejdMZTNYZnRhdytL
            U2FydTI0ZnJyRWRSMzNXZzliUURNYmdzVkRZClRONG1WcGNPZmpuOTh2N05rWThP
            Qyt4Mk1Ic2d0Zmd0aTZEaEpKV0ViQkEKLS0tIGVTZ25WOWFBZHJmSlROLzNrN01m
            aVVueEEyYXF0WGJNMG40WXEyOG51ZEUKegTYiBtXiA9sIjlK6W9yWLKqALMtrS+z
            ItjR51GYva7qYYR6kOFWTdtxRe6C1eGh+2bDUzZOyfrLIzpLEDNjPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T10:34:29Z"
    mac: ENC[AES256_GCM,data:X38BjYSUC87q/SoOpzWsUQ+7hNBMvxL+hy2iSqcWJkux1Wj92zU972SlrHk0GW9RVGpt+A2zt6h7FmFLmj94kGDtqeG3YIfL0YRN2pzm6ePHaHPE0+E+bWl/28PBd25+2tPEDjh+S6QmZ4R8tF6SolAyE6B4WceV8wfQt4L8VG8=,iv:73AHheXgibd+dvP/kn9MLmDUUKMdxTc55u7V0O8gtRc=,tag:cQrxALGsc4fULeC2S3SI8Q==,type:str]
    pgp:
        - created_at: "2025-12-29T20:44:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWXc/otv8sz4SAQdA31I2Bpxcp5geuCWSxwN5T1yzlC3eTv0l0jL/qVA4pD8w
            7WpbyVtcNvDJSw+OV1G15vMowvAgPNlcysejxWr4Ut+pmkCyqoE7RjFlIHRIS/8q
            0l4BUkkNj0T49GhzFQeno9UQm7r6selNVqOTWSb2WYGomulfedN3WY+xaGVXdFAc
            huY+8XMc3V65oWPPcm7Zvd2QF+F4XeGrxk2OxKRGibX/nozDe3wdq4Cses9HXWuy
            =LOGN
            -----END PGP MESSAGE-----
          fp: 4F0758D4AAE24E6D5A4483C666A20525398E18D7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
